os: osx
osx_image: xcode8
language: objective-c

env:
  global:
     - THEOS=~/theos

before_install:
  - brew update
  - brew install dpkg ldid xz
  - sudo cpan IO::Compress::Lzma
  - git clone --recursive git://github.com/theos/theos.git ~/theos

script:
   - make package
   - curl --upload-file ./debs/*.deb https://transfer.sh/ 
